apiVersion: v2
name: bookshelf
description: A Helm chart for deploying Bookshelf (Readarr fork)
type: application
version: 0.1.0
appVersion: "hardcover"
dependencies:
- name: library
  version: 0.0.0
  repository: file://../library
