---
apiVersion: v2
name: loki
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: node-feature-discovery # https://artifacthub.io/packages/helm/node-feature-discovery/node-feature-discovery
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: ">=0.17.2"
