{{- if .Values.serviceAccount.create -}}
{{- include "library.serviceaccount" (list . "rreading-glasses-db.serviceaccount") -}}
{{- end -}}
{{- define "rreading-glasses-db.serviceaccount" -}}
{{- end -}}
