minecraft:
  name: minecraft-server

  image: registry.hub.docker.com/itzg/minecraft-server
  tag: "2024.6.1"

  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.4.51 # Ensure static IP
    labels: {}
    port: 25569
    type: LoadBalancer

  additionalServices:
    minecraft-http:
      port: 8100
      type: ClusterIP
    metrics:
      port: 9940
      type: ClusterIP
      labels:
        service: metrics

  resources:
    requests:
      cpu: 1000m
      memory: 3Gi
    limits:
      cpu: 4000m
      memory: 8Gi

  env:
    EULA: "TRUE"
    VERSION: "1.21"
    PAPER_BUILD: "27"
    TZ: America/New_York
    TYPE: PAPER
    USE_AIKAR_FLAGS: "true"
    INIT_MEMORY: 2G
    MAX_MEMORY: 6G
    OVERRIDE_SERVER_PROPERTIES: "true"
    SPIGET_RESOURCES: 83557,81534,27021,18494,83767,57242,91208
    CURSEFORGE_FILES: |
      https://www.curseforge.com/minecraft/bukkit-plugins/customcrafting-advanced-custom-recipes/download/4655562
      https://www.curseforge.com/minecraft/bukkit-plugins/dead-chest/download/5382232
      https://www.curseforge.com/minecraft/bukkit-plugins/spawnersilk/download/5382326
      https://www.curseforge.com/minecraft/bukkit-plugins/thizzyz-tree-feller/download/5341652
      https://www.curseforge.com/minecraft/bukkit-plugins/wolfyutilities/download/4664168
      https://www.curseforge.com/minecraft/bukkit-plugins/yetanotherharvest/download/4301100
    PLUGINS: |
      https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.0/minecraft-prometheus-exporter-3.1.0.jar
    SERVER_NAME: "Central Station"
    VIEW_DISTANCE: "24"
    MAX_PLAYERS: "20"
    PLAYER_IDLE_TIMEOUT: "30"
    MOTD: "Glory to the beans hole\nView the map at http://map.drewburr.com"
    MAX_TICK_TIME: "-1"
    ENABLE_AUTOPAUSE: "false"
    JVM_DD_OPTS: disable.watchdog:true,paper.playerconnection.keepalive:60
    AUTOPAUSE_TIMEOUT_EST: "120"
    AUTOPAUSE_TIMEOUT_INIT: "60"
    AUTOPAUSE_TIMEOUT_KN: "20"
    # PLUGINS: |
    #   https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v3.20/BlueMap-3.20-paper.jar

  envFrom:
  - secretRef:
      name: curseforge-api-key

  persistence:
    name: minecraft-data
    path: /data
    resources:
      requests:
        storage: 100Gi
    accessModes:
      - ReadWriteOnce
    storageClass: zfs-nvmeof

  initContainers:
    - name: config-copy
      image: "{{ .Values.bluemap.image }}:{{ .Values.bluemap.tag }}"
      command: ['sh', '-c']
      args:
        - >-
          mkdir -p /data/plugins/BlueMap &&
          cp -r /mnt/base/. /data/plugins/BlueMap &&
          cp -r /mnt/maps /data/plugins/BlueMap &&
          cp -r /mnt/storages /data/plugins/BlueMap
      volumeMounts:
        - mountPath: /mnt/base
          name: config-base
        - mountPath: /mnt/maps
          name: config-maps
        - mountPath: /mnt/storages
          name: config-storages
        - mountPath: /data
          name: data

  additionalVolumes:
    - name: config-base
      configMap:
        name: minecraft-bluemap-config-base
    - name: config-maps
      configMap:
        name: minecraft-bluemap-config-maps
    - name: config-storages
      configMap:
        name: minecraft-bluemap-config-storages

  additionalVolumeMounts: {}

  readinessProbe:
    exec:
      command:
        - mc-health
    initialDelaySeconds: 30
    failureThreshold: 24
    periodSeconds: 5
  livenessProbe:
    exec:
      command:
        - mc-health
    failureThreshold: 10
    periodSeconds: 5

  metrics:
    enabled: true # Default to false
    name: minecraft-monitor
    endpoint:
      honorLabels: true
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 30s
    selector:
      matchLabels:
        service: metrics

bluemap:
  name: bluemap
  image: ghcr.io/bluemap-minecraft/bluemap
  tag: v5.2
  ingress:
    host: map.drewburr.com
