minecraft:
  name: minecraft-server

  image: registry.hub.docker.com/itzg/minecraft-server
  tag: "2024.6.1"

  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.4.51 # Ensure static IP
      mc-router.itzg.me/externalServerName: centralstation.mc.drewburr.com
    labels: {}
    port: 25569
    type: LoadBalancer

  additionalServices:
    minecraft-http:
      port: 8100
      type: ClusterIP
    metrics:
      port: 9940
      type: ClusterIP
      labels:
        service: metrics

  resources:
    requests:
      cpu: 2
      memory: 20Gi
    limits:
      cpu: 8
      memory: 20Gi

  env:
    EULA: "TRUE"
    VERSION: "1.21"
    PAPER_CHANNEL: experimental
    TZ: America/New_York
    # PAPER_BUILD: "38"
    TYPE: PAPER
    USE_AIKAR_FLAGS: "true"
    INIT_MEMORY: 2G
    MAX_MEMORY: 16G
    OVERRIDE_SERVER_PROPERTIES: "true"
    REMOVE_OLD_MODS: "true"
    SPIGET_RESOURCES: "83557,81534,83767"
    # https://www.spigotmc.org/resources/bluemap.83557/
    # https://www.spigotmc.org/resources/chunky.81534/
    # https://www.spigotmc.org/resources/huskhomes-1-16-1-20-set-homes-warps-spawn-tp-and-tpa-public-homes-works-cross-server.83767/
    # https://www.spigotmc.org/resources/clicksort.27021/
    # https://www.spigotmc.org/resources/spark.57242/
    # https://www.spigotmc.org/resources/item-effects.91208/
    PLUGINS: |
      https://mediafilez.forgecdn.net/files/5382/232/dead-chest-4.21.0.jar
      https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.0/minecraft-prometheus-exporter-3.1.0.jar
      https://mediafilez.forgecdn.net/files/4301/100/YetAnotherHarvest-1.1.jar
      https://snapshot.discordsrv.com/discordsrv.jar
    # https://get.discordsrv.com/discordserv.jar # Release version
    #   https://mediafilez.forgecdn.net/files/5382/326/spawner-silk-5.7.0.jar
    # https://mediafilez.forgecdn.net/files/5341/652/TreeFeller-1.23.1.jar
    # https://dev.bukkit.org/projects/customcrafting-advanced-custom-recipes
    # https://dev.bukkit.org/projects/dead-chest
    # https://dev.bukkit.org/projects/spawnersilk
    # https://dev.bukkit.org/projects/wolfyutilities
    # https://dev.bukkit.org/projects/yetanotherharvest
    # https://dev.bukkit.org/projects/thizzyz-tree-feller # Causes server crash (6/23/24)
    SERVER_NAME: "Central Station"
    VIEW_DISTANCE: "24"
    MAX_PLAYERS: "20"
    PLAYER_IDLE_TIMEOUT: "30"
    MOTD: "Glory to the beans hole\nView the map at http://map.drewburr.com"
    MAX_TICK_TIME: "-1"
    USES_PROXY_PROTOCOL: "true"
    ONLINE_MODE: "true"
    ENABLE_AUTOPAUSE: "false"
    JVM_DD_OPTS: disable.watchdog:true,paper.playerconnection.keepalive:60
    AUTOPAUSE_TIMEOUT_EST: "120"
    AUTOPAUSE_TIMEOUT_INIT: "60"
    AUTOPAUSE_TIMEOUT_KN: "20"
    # PLUGINS: |
    #   https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v3.20/BlueMap-3.20-paper.jar

  envFrom: []

  persistence:
    name: minecraft-data
    path: /data
    resources:
      requests:
        storage: 100Gi
    accessModes:
      - ReadWriteOnce
    storageClass: zfs-nvmeof

  initContainers: []

  additionalVolumeMounts: {}

  readinessProbe:
    exec:
      command:
        - mc-monitor
        - status
        - -use-proxy
    initialDelaySeconds: 30
    failureThreshold: 36
    periodSeconds: 5
  livenessProbe:
    exec:
      command:
        - mc-monitor
        - status
        - -use-proxy
    failureThreshold: 10
    periodSeconds: 5

  metrics:
    enabled: true # Default to false
    name: minecraft-monitor
    endpoint:
      honorLabels: true
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 30s
    selector:
      matchLabels:
        service: metrics

bluemap:
  name: bluemap
  image: ghcr.io/bluemap-minecraft/bluemap
  tag: v5.2
  ingress:
    host: map.drewburr.com
