apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack # https://github.com/prometheus-community/helm-charts/tree/kube-prometheus-stack-51.2.0/charts/kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: ">=67.x.x"
