---
kube-prometheus-stack:
  crds:
    enabled: false

  prometheus:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      ingressClassName: traefik
      hosts:
      - prometheus.drewburr.com
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.drewburr.com
      pathType: ImplementationSpecific

    prometheusSpec:
      serviceMonitorSelector:
        matchLabels: null

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: zfs-nvmeof
            resources:
              requests:
                storage: 50Gi

      global:
        external_labels:
          cluster: "k3s"

      retention: 30d

      resources: {}

      additionalScrapeConfigs:
      - job_name: kube-etcd
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file:   /etc/prometheus/secrets/etcd-client-cert/etcd-ca
          cert_file: /etc/prometheus/secrets/etcd-client-cert/etcd-client
          key_file:  /etc/prometheus/secrets/etcd-client-cert/etcd-client-key
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - source_labels: [__address__]
          action: replace
          targetLabel: __address__
          regex: ([^:;]+):(\d+)
          replacement: ${1}:2379
        - source_labels: [__meta_kubernetes_node_name]
          action: keep
          regex: .*mst.*
        - source_labels: [__meta_kubernetes_node_name]
          action: replace
          targetLabel: node
          regex: (.*)
          replacement: ${1}
        metric_relabel_configs:
        - regex: (kubernetes_io_hostname|failure_domain_beta_kubernetes_io_region|beta_kubernetes_io_os|beta_kubernetes_io_arch|beta_kubernetes_io_instance_type|failure_domain_beta_kubernetes_io_zone)
          action: labeldrop

    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      separator: ;
      regex: ^(.*)$
      targetLabel: nodename
      replacement: $1
      action: replace

  grafana:
    admin:
      existingSecret: "prometheus-grafana"

    # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
    env:
      GF_AUTH_ANONYMOUS_ENABLED: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      ingressClassName: traefik
      hosts:
      - grafana.drewburr.com
      tls:
      - secretName: grafana-tls
        hosts:
        - grafana.drewburr.com

    persistence:
      enabled: true
      storageClassName: zfs-nvmeof
      size: 20Gi

    resources:
     limits:
       cpu: 1000m
       memory: 1Gi
    #  requests:
    #    cpu: 100m
    #    memory: 128Mi

  kubelet:
    serviceMonitor:
      resource: true
      resource_path: /metrics/resource
