---
kube-prometheus-stack:
  crds:
    enabled: false

  prometheus:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      ingressClassName: traefik
      hosts:
      - prometheus.drewburr.com
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.drewburr.com
      pathType: ImplementationSpecific

    prometheusSpec:
      serviceMonitorSelector:
        matchLabels: null

  grafana:
    admin:
      existingSecret: "prometheus-grafana"

    # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
    env:
      GF_AUTH_ANONYMOUS_ENABLED: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      ingressClassName: traefik
      hosts:
      - grafana.drewburr.com
      tls:
      - secretName: grafana-tls
        hosts:
        - grafana.drewburr.com
