apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: query-stream-modify
spec:
  plugin:
    traefik-plugin-query-modification:
      NewValue: stream
      ParamName: action
      Type: modify
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: query-stream-add
spec:
  plugin:
    traefik-plugin-query-modification:
      NewValue: stream
      ParamName: action
      Type: add
