user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  text/html;
  access_log off;

  server {
    listen 8080;

    location / {
      root /usr/share/nginx/html;

      set $page "503.html";
      if ($http_x_code = "404") {
        set $page "404.html";
      }

      try_files /$page /503.html;
    }
  }
}
