{{- range $name, $conf := .Values.services }}
{{- if $conf.ingress }}
{{- $fullName := include "plex.fullname" $ -}}
{{- $svcPort := $conf.port -}}
{{- if $conf.ingress.className }}
  {{- if not (hasKey $conf.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $conf.ingress.annotations "kubernetes.io/ingress.class" $conf.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "plex.labels" $ | nindent 4 }}
  {{- with $conf.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $conf.ingress.className }}
  {{- if $conf.ingress.tls }}
  tls:
    {{- range $conf.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $conf.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}-{{ $name }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
