---
kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-daemon-config
  namespace: {{ .Release.Namespace }}
  labels:
    tier: node
    app: multus
data:
  daemon-config.json: |
    {
        "chrootDir": "/hostroot",
        "cniVersion": "0.3.1",
        "logLevel": {{ .Values.daemonConfig.logLevel | quote }},
        "logToStderr": {{ .Values.daemonConfig.logToStderr }},
        "cniConfigDir": "/host/etc/cni/net.d",
        "multusAutoconfigDir": "/host/etc/cni/net.d",
        "multusConfigFile": "auto",
        "socketDir": "/host/run/multus/",
        "binDir": {{ .Values.cni.binDir | quote }},
        "clusterNetwork": {{ .Values.daemonConfig.clusterNetwork | quote }}
    }
