{{- range .Values.endpoints }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
  labels:
    {{- toYaml $.Values.labels | nindent 4 }}
spec:
  type: ExternalName
  ports:
    - port: {{ $.Values.port }}
      targetPort: {{ $.Values.port }}
      protocol: TCP
      name: http
  externalName: {{ .url | quote }}
{{- end }}
