{{- range .Values.endpoints }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | quote }}
  labels:
    {{- toYaml $.Values.labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.port }}
      targetPort: {{ $.Values.port }}
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name | quote }}
  labels:
    {{- toYaml $.Values.labels | nindent 4 }}
subsets:
  addresses:
  - ip: {{ .ip }}
  ports:
  - name: http
    port: 9100
{{- end }}
