---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-rwo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: zfs-nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-rwo-deployment
  name: example-rwo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-rwo-deployment
  template:
    metadata:
      labels:
        app: example-rwo-deployment
    spec:
      containers:
      - image: ubuntu
        imagePullPolicy: Always
        name: ubuntu
        command: ['sh', '-c', 'tail -f /dev/null']
        resources: {}
        volumeMounts:
        - name: pvc
          mountPath: /pvc
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: example-rwo-pvc
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: example-rwo-deployment
