# https://github.com/kashalls/external-dns-unifi-webhook
---
external-dns:
  provider:
    name: cloudflare
  labelFilter: cloudflare-dns='true'
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-key
          key: apiKey
  policy: sync
  sources: ['service']
  txtOwnerId: default
  txtPrefix: k8s.
  domainFilters: ['drewburr.com']
  managedRecordTypes:
    - CNAME

  serviceMonitor:
    enabled: true
