---
applications:
- name: argocd
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: cert-manager
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: metallb
  destination:
    namespace: metallb-system
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
  ignoreDifferences: # https://github.com/metallb/metallb/issues/1681
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: addresspools.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
- name: metrics-server
  destination:
    namespace: metrics-server
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: prometheus
  destination:
    namespace: kube-prometheus-stack
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: prometheus-crds
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
- name: traefik
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: democratic-csi-local
  destination:
    namespace: democratic-csi
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: democratic-csi-zfs-nvmeof
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: minecraft
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: minecraft-paper
  syncPolicy:
    automated: {}
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: evobot
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: system-upgrade-controller
  destination:
    namespace: system-upgrade
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: geist-pdu-exporter
  syncPolicy:
    automated: {}
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: dcsi-snapshot-controller
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
