---
applications:
- name: ceph
  destination:
    namespace: ceph-csi-rbd
  targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: cert-manager
  targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: metallb
  destination:
    namespace: metallb-system
  targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: metrics-server
  targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
- name: prometheus
  destination:
    namespace: kube-prometheus-stack
  targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - Replace=true
- name: traefik
  targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
