{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "panel.fullname" $ }}-{{ .name }}
  labels:
    {{- include "panel.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  ports:
    {{- toYaml .ports | nindent 4 }}
  selector:
    {{- include "panel.selectorLabels" $ | nindent 4 }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
{{- end }}
