# https://github.com/kashalls/external-dns-unifi-webhook
---
external-dns:
  labelFilter:
    dnsProvider: unifi
  provider:
    name: webhook
    webhook:
      image:
        repository: ghcr.io/kashalls/external-dns-unifi-webhook
        tag: v0.3.3
      env:
        - name: UNIFI_HOST
          value: https://192.168.4.1
        - name: UNIFI_EXTERNAL_CONTROLLER
          value: 'false'
        - name: UNIFI_USER
          valueFrom:
            secretKeyRef:
              name: unifi-credentials
              key: username
        - name: UNIFI_PASS
          valueFrom:
            secretKeyRef:
              name: unifi-credentials
              key: password
        - name: LOG_LEVEL
          value: INFO
      livenessProbe:
        httpGet:
          path: /healthz
          port: http-webhook
        initialDelaySeconds: 10
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /readyz
          port: http-webhook
        initialDelaySeconds: 10
        timeoutSeconds: 5
  extraArgs:
    - --ignore-ingress-tls-spec
  policy: sync
  sources: ['ingress', 'service']
  txtOwnerId: default
  txtPrefix: k8s.
  domainFilters: ['drewburr.com']
