---
# name defaults to "archiveteam-grab"
# TODO: Parse the image name to generate a default name
# nameOverride:

image: atdr.meo.ws/archiveteam/mildom-grab

replicas: 9

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

# See: https://wiki.archiveteam.org/index.php/Running_Archive_Team_Projects_with_Docker#Stopping_containers
# SIGINT is preferrable, but not supported.
terminationGracePeriodSeconds: 3600

updateStrategy:
  rollingUpdate:
    maxUnavailable: 100%

grabArgs:
  concurrency: '1'
  username: drewburr

persistence:
  # By default, each pod will receive its own PVC.
  # If `unified: true`, all pods will share one PVC.
  unified: false
  # To prevent ephemeralStorage issues, encapsulate the workDir in the PVC
  encapsulateWorkdir: true

  storageClass: zfs-nvmeof
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
