---
# name defaults to "archiveteam-grab"
# TODO: Parse the image name to generate a default name
# nameOverride:

image: atdr.meo.ws/archiveteam/mildom-grab

replicas: 9

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

# See: https://wiki.archiveteam.org/index.php/Running_Archive_Team_Projects_with_Docker#Stopping_containers
# SIGINTis preferrable, but not supported.
terminationGracePeriodSeconds: 3600

grabArgs:
  username: drewburr
  concurrency: '10'

persistence:
  # By default, each pod will receive its own PVC.
  # If `unified: true`, all pods will share one PVC.
  unified: false
  storageClass: zfs-nvmeof
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
