---
# name defaults to the name of the image beliw (e.g. mildom-grab)
# nameOverride:

image: atdr.meo.ws/archiveteam/mildom-grab

replicas: 9

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

grabArgs:
  username: drewburr
  concurrency: '10'

persistence:
  name: cache-volume
  storageClass: zfs-nvmeof
  resources:
    requests:
      storage: 3Ti
  accessModes:
    - ReadWriteOnce
