---
apiVersion: v2
name: evobot
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: evobot # https://github.com/drewburr-labs/evobot
    repository: https://drewburr-labs.github.io/evobot
    version: ^0.1.1
