---
traefik:
  additionalArguments:
  - "--serversTransport.insecureskipverify=true"
  - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik-internal/traefik-internal" # Kubernetes service to copy status from
  - "--providers.kubernetescrd.allowemptyservices=true"
  - "--providers.kubernetescrd.allowexternalnameservices=true"
  - "--providers.kubernetesingress.allowemptyservices=true"
  - "--providers.kubernetesingress.allowexternalnameservices=true"
  logs:
    general:
      level: INFO

  deployment:
    kind: DaemonSet

  providers:
    kubernetesCRD:
      # Public ingress to manage CRDs
      enabled: false

  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.4.60 # Ensure static IP

  ingressRoute:
    dashboard:
      matchRule: Host(`traefik-internal.drewburr.com`)
      entryPoints:
      - web

  metrics:
    prometheus:
      disableAPICheck: true # Don't check for monitoring.coreos.com/v1
      service:
        enabled: true # Enable dedicated Prometheus metrics service

      serviceMonitor:
        enabled: true
        metricRelabelings:
          - sourceLabels: [__name__]
            separator: ;
            regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
            replacement: $1
            action: drop
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            separator: ;
            regex: ^(.*)$
            targetLabel: nodename
            replacement: $1
            action: replace
        jobLabel: traefik-internal
        interval: 30s
        honorLabels: true

  ingressClass:
    isDefaultClass: false
    name: traefik-internal

  experimental:
    plugins:
      # https://plugins.traefik.io/plugins/628c9f24ffc0cd18356a97bd/query-paramter-modification
      traefik-plugin-query-modification:
        moduleName: "github.com/kingjan1999/traefik-plugin-query-modification"
        version: "v1.0.0"
