---
minecraft:
  resources:
    requests:
      memory: 6Gi
      cpu: 1
    limits:
      memory: 6Gi
      cpu: 4

  minecraftServer:
    eula: TRUE
    type: PAPER
    version: LATEST
    overrideServerProperties: true
    motd: Welcome to the Toilet Bowl!
    difficulty: easy
    # A comma-separated list of player names who should be admins.
    # ops: drebwurr
    maxWorldSize: 29999984
    worldSaveName: lou
    maxPlayers: 20
    viewDistance: 14

    rcon:
      enabled: true
      existingSecret: rcon-auth
      secretKey: rcon-password

  serviceAnnotations:
    mc-router.itzg.me/externalServerName: toiletbowl.mc.drewburr.com

  extraEnv:
    TZ: America/New_York
    USE_AIKAR_FLAGS: "true"
    INIT_MEMORY: 2G
    MAX_MEMORY: 5G
    PLAYER_IDLE_TIMEOUT: "30"
    USES_PROXY_PROTOCOL: "true"
    # Autopause settings
    MAX_TICK_TIME: "-1"
    ENABLE_AUTOPAUSE: "true"
    AUTOPAUSE_KNOCK_INTERFACE: eth0
    JVM_DD_OPTS: disable.watchdog:true,paper.playerconnection.keepalive:60
    AUTOPAUSE_TIMEOUT_EST: "120"
    AUTOPAUSE_TIMEOUT_INIT: "60"
    AUTOPAUSE_TIMEOUT_KN: "20"

  readinessProbe:
    command:
      - mc-monitor
      - status
      - -use-proxy
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 1

  livenessProbe:
    command:
      - mc-monitor
      - status
      - -use-proxy
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 1

  persistence:
    storageClass: zfs-nvmeof
    dataDir:
      enabled: true
      Size: 20Gi
      accessModes:
        - ReadWriteOnce

  mcbackup:
    enabled: true
    persistence:
      existingClaim: false
      storageClass: zfs-nvmeof
      backupDir:
        enabled: true
        Size: 100Gi
        accessModes:
          - ReadWriteOnce
