---
minecraft:
  resources:
    requests:
      memory: 6Gi
      cpu: 1
    limits:
      memory: 6Gi
      cpu: 4

  minecraftServer:
    eula: TRUE
    type: PAPER
    version: LATEST
    overrideServerProperties: true
    motd: Welcome to the Toilet Bowl!
    difficulty: easy
    # A comma-separated list of player names who should be admins.
    # ops: drebwurr
    maxWorldSize: 29999984
    worldSaveName: lou
    maxPlayers: 20
    viewDistance: 14

    rcon:
      enabled: true
      existingSecret: rcon-auth
      secretKey: rcon-password

    extraPorts:
      - name: map
        containerPort: 8100
        protocol: TCP
        service:
          enabled: true
          type: ClusterIP
          port: 8100
        ingress:
          ingressClassName: traefik
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - name: toiletbowl.map.drewburr.com
              path: /
          tls:
            - secretName: map-tls
              hosts:
                - toiletbowl.map.drewburr.com
      - name: metrics
        containerPort: 9940
        protocol: TCP
        service:
          enabled: true
          type: ClusterIP
          port: 9940
        ingress: {}

  serviceAnnotations:
    mc-router.itzg.me/externalServerName: toiletbowl.mc.drewburr.com

  extraEnv:
    TZ: America/New_York
    USE_AIKAR_FLAGS: "true"
    INIT_MEMORY: 2G
    MAX_MEMORY: 5G
    PLAYER_IDLE_TIMEOUT: "30"
    USES_PROXY_PROTOCOL: "true"
    # Autopause settings
    MAX_TICK_TIME: "-1"
    ENABLE_AUTOPAUSE: "true"
    AUTOPAUSE_KNOCK_INTERFACE: eth0
    JVM_DD_OPTS: disable.watchdog:true,paper.playerconnection.keepalive:60
    AUTOPAUSE_TIMEOUT_EST: "120"
    AUTOPAUSE_TIMEOUT_INIT: "60"
    AUTOPAUSE_TIMEOUT_KN: "20"
    # Plugins
    REMOVE_OLD_MODS: "true"
    SPIGET_RESOURCES: "83557,81534"
    # https://www.spigotmc.org/resources/bluemap.83557/
    # https://www.spigotmc.org/resources/chunky.81534/
    PLUGINS: |
      https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.3/BlueMap-5.3-paper.jar
      https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v3.1.0/minecraft-prometheus-exporter-3.1.0.jar
      https://snapshot.discordsrv.com/discordsrv.jar

  readinessProbe:
    command:
      - mc-monitor
      - status
      - -use-proxy
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 1

  livenessProbe:
    command:
      - mc-monitor
      - status
      - -use-proxy
    initialDelaySeconds: 30
    periodSeconds: 5
    failureThreshold: 20
    successThreshold: 1
    timeoutSeconds: 1

  persistence:
    storageClass: zfs-nvmeof
    dataDir:
      enabled: true
      Size: 20Gi
      accessModes:
        - ReadWriteOnce

  mcbackup:
    enabled: true
    persistence:
      existingClaim: false
      storageClass: zfs-nvmeof
      backupDir:
        enabled: true
        Size: 100Gi
        accessModes:
          - ReadWriteOnce

serviceMonitor:
  enabled: true
  endpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
    scheme: http
    scrapeTimeout: 30s
