---
apiVersion: v1
kind: Service
metadata:
  name: secret-palpatine
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: secret-palpatine
  ports:
    - name: http
      port: 80
      targetPort: http
