---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: secret-palpatine
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
    app: secret-palpatine
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: secret-palpatine
