---
apiVersion: v2
name: loki
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: loki # https://github.com/grafana/loki/tree/main/production/helm/loki
    repository: https://grafana.github.io/helm-charts
    version: ^6.25.0
