---
device-plugin-operator:
  resources:
    limits:
      cpu: 100m
      memory: 120Mi
    requests:
      cpu: 100m
      memory: 100Mi

  manager:
    # supported devices by the operator
    devices:
      # dlb: true
      # dsa: true
      # fpga: true
      gpu: true
      # iaa: true
      # qat: true
      # sgx: true

gpuDevicePlugin:
  image:
    # https://hub.docker.com/r/intel/intel-gpu-plugin/tags
    path: intel/intel-gpu-plugin
    tag: '0.32.0'
  # https://intel.github.io/intel-device-plugins-for-kubernetes/cmd/gpu_plugin/README.html#modes-and-configuration-options
  sharedDevNum: 10
  logLevel: 4
  enableMonitoring: true
