{{- define "library.ingresses" -}}
---
{{- range $service := .Values.services }}
{{- if ($service).ingress }}
{{- $fullName := include "library.fullname" $ -}}
{{- $svcPort := .port -}}
{{- if .ingress.className }}
  {{- if not (hasKey .ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .ingress.annotations "kubernetes.io/ingress.class" .ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $service.name }}
  labels:
    {{- include "library.labels" $ | nindent 4 }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .ingress.className }}
  {{- if .ingress.tls }}
  tls:
    {{- range $tls := .ingress.tls }}
    - hosts:
        {{- range $tls.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ $tls.secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $host := .ingress.hosts }}
    - host: {{ $host.host | quote }}
      http:
        paths:
          {{- range $path := $host.paths }}
          - path: {{ $path.path }}
            {{- if $path.pathType }}
            pathType: {{ $path.pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}-{{ $service.name }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end -}}
