{{- define "library.serviceaccount.tpl" -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "library.serviceAccountName" . }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}}
{{- define "library.serviceaccount" -}}
{{- include "library.util.merge" (append . "library.serviceaccount.tpl") -}}
{{- end -}}
