{{- define "library.deployment.tpl" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "library.fullname" . }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "library.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "library.selectorLabels" . | nindent 8 }}
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 192.168.4.1
          - 1.1.1.1
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "library.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $k, $v := .Values.envVars }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
            {{- end }}
          ports:
            {{- range .Values.services }}
            - containerPort: {{ .port }}
              protocol: {{ .protocol }}
              name: {{ .name }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.persistence }}
            - name: {{ .name }}
              mountPath: /{{ default .name .mountPath }}
            {{- end }}
            {{- range $.Values.additionalVolumeMounts }}
            {{ list . | toYaml | nindent 12 }}
            {{- end }}
      initContainers:
      {{- range $initContainer := .Values.initContainers }}
      - name: {{ $initContainer.name }}
        securityContext:
          {{- toYaml $initContainer.securityContext | nindent 10 }}
        image: "{{ $initContainer.image.repository }}:{{ $initContainer.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ $initContainer.image.pullPolicy }}
        command:
          {{- toYaml $initContainer.command | nindent 10 }}
        env:
          {{- range $k, $v := $.Values.envVars }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
          {{- end }}
          {{- range $k, $v := $initContainer.envVars }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
          {{- end }}
        resources:
          {{- toYaml $initContainer.resources | nindent 10 }}
        volumeMounts:
          {{- range $.Values.persistence }}
          - name: {{ .name }}
            mountPath: /{{ default .name .mountPath }}
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- range .Values.persistence }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .name }}
        {{- end }}
        {{- range .Values.additionalVolumes }}
        {{ list . | toYaml | nindent 8 }}
        {{- end }}
{{- end -}}
{{- define "library.deployment" -}}
{{- include "library.util.merge" (append . "library.deployment.tpl") -}}
{{- end -}}
