open-webui:
  ollama:
    enabled: false

  ollamaUrls: []

  openaiBaseApiUrl: "http://192.168.4.56:8000/v1"
  openaiApiKey: "none"

  pipelines:
    enabled: false

  persistence:
    enabled: true
    size: 5Gi
    storageClass: zfs-nvmeof

  ingress:
    enabled: true
    class: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/hostname: openwebui.drewburr.com
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    host: openwebui.drewburr.com
    tls: true
