open-webui:
  ollama:
    enabled: false

  ollamaUrls: []

  extraEnvVars:
    - name: OPENAI_API_BASE_URL
      value: http://192.168.4.56:8000/v1
    - name: OPENAI_API_KEY
      value: none

  pipelines:
    enabled: false

  persistence:
    enabled: true
    size: 5Gi
    storageClass: zfs-nvmeof

  ingress:
    enabled: true
    class: nginx-internal
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/hostname: openwebui.drewburr.com
    host: openwebui.drewburr.com
    tls: true
