apiVersion: v2
name: ingress-nginx-internal
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: ingress-nginx # hhttps://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: ">=4.11.3"
