---
ingress-nginx:

  controller:
    kind: Daemonset

    ingressClassResource:
      name: nginx-internal
      controllerValue: k8s.io/ingress-nginx-internal
    ingressClass: nginx-internal

    resources:
      requests:
        cpu: 100m
        memory: 90Mi

    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: '192.168.4.61'

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
