apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vpn-secure
spec:
  config: |
    {
      "cniVersion": "1.1.0",
      "type": "macvlan",
      "master": "ens19",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp",
        "provide": [
          {
            "option": "host-name",
            "fromArg": "K8S_POD_NAME"
          }
        ]
      }
    }
