apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: bluemap
spec:
  ingressClassName: traefik
  rules:
  - host: map.drewburr.com
    http:
      paths:
      - backend:
          service:
            name: bluemap
            port:
              name: bluemap-http
        path: /maps/{path:[a-zA-Z]+}/tiles/
        pathType: Prefix
      - backend:
          service:
            name: {{ .Values.minecraft.name }}-bluemap
            port:
              name: http
        path: /maps/{path:[a-zA-Z]+}/live/
        pathType: Prefix
  tls:
  - hosts:
    - map.drewburr.com
    secretName: bluemap-server-tls
