apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluemap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluemap
  template:
    metadata:
      labels:
        app: bluemap
    spec:
      containers:
        - image: ghcr.io/bluemap-minecraft/bluemap:latest
          name: bluemap
          ports:
            - containerPort: 8100
          args:
            - -r
            - -u
            - -w
          resources: {}
          volumeMounts:
            - mountPath: /app/config
              name: bluemap-config
            - mountPath: /app/data
              name: bluemap-data
            - mountPath: /app/web
              name: bluemap-web
            - mountPath: /app/minecraft-data
              name: minecraft-data
            - mountPath: /bluemap-config
              name: bluemap-config
            - mountPath: /mnt/config-base
              name: config-base
            - mountPath: /mnt/config-maps
              name: config-maps
            - mountPath: /mnt/config-storages
              name: config-storages
      restartPolicy: Always
      volumes:
        - name: bluemap-data
          persistentVolumeClaim:
            claimName: bluemap-data
        - name: bluemap-web
          persistentVolumeClaim:
            claimName: bluemap-web
        - name: bluemap-config
          emptyDir: {}
        - name: config-base
          configMap:
            name: bluemap-config-base
        - name: config-maps
          configMap:
            name: bluemap-config-maps
        - name: config-storages
          configMap:
            name: bluemap-config-storages
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
