apiVersion: v1
kind: Service
metadata:
  name: bluemap
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.4.52 # Ensure static IP
spec:
  ports:
    - name: bluemap
      port: 80
      targetPort: 8100
  selector:
    app: bluemap
  type: LoadBalancer
