{{- with .Values.minecraft.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    {{- toYaml .resources | nindent 4 }}
  storageClassName: {{ .storageClass }}
{{- end }}
