apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.4.51 # Ensure static IP
spec:
  ports:
    - name: minecraft
      port: 25569
      targetPort: 25565
  selector:
    app: minecraft-server
  type: LoadBalancer
