---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minecraft.name }}
  annotations:
    {{- toYaml .Values.minecraft.service.annotations | nindent 4 }}
  labels:
    {{- toYaml .Values.minecraft.service.labels | nindent 4 }}
spec:
  ports:
    - name: minecraft
      port: {{ .Values.minecraft.service.port }}
      targetPort: minecraft
  selector:
    app: {{ .Values.minecraft.name }}
  type: {{ .Values.minecraft.service.type }}
{{- range $name, $spec := .Values.minecraft.additionalServices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  annotations:
    {{- toYaml $.Values.minecraft.service.annotations | nindent 4 }}
  labels:
    {{- toYaml $.Values.minecraft.service.labels | nindent 4 }}
spec:
  ports:
    - name: {{ $name }}
      port: {{ $spec.port }}
      targetPort: {{ $name }}
  selector:
    app: {{ $.Values.minecraft.name }}
  type: {{ $.Values.minecraft.service.type }}
{{- end }}
