---
apiVersion: v2
name: external-secrets
description: External Secrets Operator + shared-secrets distribution store
type: application
version: 0.1.0
dependencies:
  - name: external-secrets # https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
    repository: https://charts.external-secrets.io
    version: ">=0.10.0"
