---
promtail:
  resources: {}
  #  limits:
  #    cpu: 200m
  #    memory: 128Mi
  #  requests:
  #    cpu: 100m
  #    memory: 128Mi

  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0

  config:
    clients:
      - url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
        config:
    snippets:
      extraScrapeConfigs: |
        # Add an additional scrape config for syslog
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
            labels:
              job: syslog
          relabel_configs:
            - source_labels:
                - __syslog_message_hostname
              target_label: hostname

            # example label values: kernel, CRON, kubelet
            - source_labels:
                - __syslog_message_app_name
              target_label: app

            # example label values: debug, notice, informational, warning, error
            - source_labels:
                - __syslog_message_severity
              target_label: level

  extraPorts:
    # Enable syslog support
    syslog:
      name: tcp-syslog
      containerPort: 1514
      service:
        port: 80
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.4.63
