apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.bluemap.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.bluemap.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.bluemap.name }}
    spec:
      containers:
        - name: bluemap
          image: {{ .Values.bluemap.image }}:{{ .Values.bluemap.tag }}
          ports:
            - name: bluemap
              containerPort: 8100
          args:
            - -r
            - -u
            - -w
          resources:
            requests:
              cpu: 2
              memory: 8Gi
            limits:
              cpu: 8
              memory: 12Gi
          volumeMounts:
            - mountPath: /app/data
              name: bluemap-data
            - mountPath: /app/web
              name: bluemap-web
            - mountPath: /app/config
              name: bluemap-config
            - mountPath: /app/minecraft-data
              name: minecraft-data
      restartPolicy: Always
      volumes:
        - name: bluemap-data
          persistentVolumeClaim:
            claimName: bluemap-data
        - name: bluemap-web
          persistentVolumeClaim:
            claimName: bluemap-web
        - name: bluemap-config
          persistentVolumeClaim:
            claimName: bluemap-configs
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
