---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluemap-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: zfs-nvmeof
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluemap-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: zfs-nvmeof
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluemap-configs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: zfs-nvmeof
