apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# https://github.com/rancher/system-upgrade-controller/tree/master/manifests
# https://github.com/kubernetes-sigs/kustomize/issues/119#issuecomment-2177235690
- https://raw.githubusercontent.com/rancher/system-upgrade-controller/latest/manifests/clusterrole.yaml
- https://raw.githubusercontent.com/rancher/system-upgrade-controller/latest/manifests/clusterrolebinding.yaml
- https://raw.githubusercontent.com/rancher/system-upgrade-controller/latest/manifests/system-upgrade-controller.yaml
- resources/upgrade-plan.yaml
patchesStrategicMerge:
- patches/fix-clusterrolebindings.yaml
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: system-upgrade-controller
  path: patches/system-upgrade-controller.yaml
