apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - https://github.com/rancher/system-upgrade-controller/blob/v0.13.2/manifests/system-upgrade-controller.yaml
- https://raw.githubusercontent.com/rancher/system-upgrade-controller/v0.13.2/manifests/system-upgrade-controller.yaml
