apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - https://github.com/rancher/system-upgrade-controller/tree/master/manifests
- https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/*
- ./upgrade-plan.yaml
