---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-latest
  namespace: system-upgrade
  labels:
    k3s-upgrade: v1.28.5
spec:
  concurrency: 1
  version: v1.28.5+k3s1
  nodeSelector:
    matchExpressions:
      - {key: k3s-upgrade, operator: Exists}
  serviceAccountName: system-upgrade
  # drain:
  #   force: true
  # cordon: true
  upgrade:
    image: rancher/k3s-upgrade
