apiVersion: v3
name: cert-manager
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: cert-manager # https://cert-manager.io/docs/installation/helm/
    version: v1.13.0
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
