apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: cert-manager # https://cert-manager.io/docs/installation/helm/
    version: ">=1.15.3"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
