apiVersion: v2
name: dex
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: dex # https://github.com/dexidp/helm-charts/tree/dex-0.16.0/charts/dex
    repository: https://charts.dexidp.io
    version: ^0.16.0
