dex:
  config:
    issuer: https://dex.drewburr.com:32000

    # See https://dexidp.io/docs/storage/ for more options
    storage:
      type: kubernetes
      config:
        inCluster: true

    # Enable at least one connector
    # See https://dexidp.io/docs/connectors/ for more options
    enablePasswordDB: true

    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $GITHUB_CLIENT_ID
          clientSecret: $GITHUB_CLIENT_SECRET
          redirectURI: https://dex.example.com:32000/callback
          org: kubernetes
    oauth2:
      skipApprovalScreen: true

    staticClients:
      - id: k3s-client
        redirectURIs:
          - "http://localhost:8000"
        name: "k3s-client"
        secret: ob2bKH9ZCyg8YtYKuCaQkZQu

  envFrom:
    - secretRef:
        name: github-client
    - secretRef:
        name: k3s-client

  volumes:
    - name: ca-certs
      hostPath:
        path: /etc/ssl/certs
        type: DirectoryOrCreate
  volumeMounts:
    - mountPath: /etc/ssl/certs
      name: etc-ssl-certs
      readOnly: true

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: dex.drewburr.com
        paths:
          - path: /
    tls:
      - hosts:
          - dex.drewburr.com
        secretName: dex-cert

  serviceMonitor:
    enabled: true
