---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
spec:
  accessModes:
  # - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-hostpath
