---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade-drainer
subjects:
  - kind: ServiceAccount
    name: system-upgrade
    namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-upgrade
subjects:
  - kind: ServiceAccount
    name: system-upgrade
    namespace: system-upgrade
