{{- range $name, $conf := .Values.persistence }}
{{- if .requests }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "radarr.fullname" $ }}-{{ $name }}
  labels:
    {{- include "radarr.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{ toYaml $conf.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $conf.requests }}
  storageClassName: {{ $conf.storageClassName }}
{{- end }}
{{- end }}
