# https://github.com/kashalls/external-dns-unifi-webhook
---
external-dns:
  provider:
    name: cloudflare
  # labelFilter: cloudflare-dns='true' # Not supported in Helm v1.15.0
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-key
          key: apiKey
  extraArgs:
    - --ingress-class=traefik
    - --ingress-class=nginx-external
    - --managed-record-types=CNAME
    - --label-filter=cloudflare-dns=true
  policy: sync
  sources: ['ingress', 'service']
  txtOwnerId: default
  txtPrefix: k8s.
  domainFilters: ['drewburr.com']
  # Not supported in Helm v1.15.0
  # managedRecordTypes:
  #   - CNAME

  serviceMonitor:
    enabled: true
