apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syslog-ng.fullname" . }}
  labels:
    {{- include "syslog-ng.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "syslog-ng.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "syslog-ng.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "syslog-ng.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- range $k, $v := . }}
            - name: {{ $k }}
              value: {{ quote $v }}
            {{- end }}
          {{- end }}
          ports:
            - name: syslogudp
              containerPort: 5514
              protocol: UDP
            - name: syslogtcp
              containerPort: 6601
              protocol: TCP
            - name: syslogtls
              containerPort: 6514
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: syslogtcp
          readinessProbe:
            tcpSocket:
              port: syslogtcp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: run
              mountPath: /run
            - name: config
              mountPath: /config
      initContainers:
        - name: config-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - sh
            - -c
            - cp /config-init/* /config/
          volumeMounts:
            - name: config
              mountPath: /config
            - name: config-init
              mountPath: /config-init
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-init
          configMap:
            name: syslog-ng-config
            optional: false
        - name: config
          emptyDir: {}
        - name: run
          emptyDir: {}
