apiVersion: v2
name: homepage
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: homepage # https://github.com/jameswynn/helm-charts/tree/main/charts/homepage
    repository: https://jameswynn.github.io/helm-charts
    version: ^26.0.0
