---
apiVersion: v1
kind: ConfigMap
metadata:
  name: error-pages
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
{{ .Files.Get "files/nginx.conf" | indent 4 }}
  503.html: |
{{ .Files.Get "files/503.html" | indent 4 }}
  404.html: |
{{ .Files.Get "files/404.html" | indent 4 }}
