---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-latest
  namespace: system-upgrade
  labels:
    k3s-upgrade: v1.31.2
spec:
  concurrency: 1
  version: v1.31.2+k3s1
  nodeSelector:
    matchExpressions:
      - key: k3s-upgrade
        operator: In
        values: [v1.31.2]
  serviceAccountName: system-upgrade
  # drain:
  #   force: true
  # cordon: true
  upgrade:
    image: rancher/k3s-upgrade
