---
kube-prometheus-stack:
  crds:
    enabled: true

  prometheus-node-exporter:
    enabled: false

  grafana:
    enabled: false

  defaultRules:
    create: false

  global:
    rbac:
      create: false

  alertmanager:
    enabled: false

  kubeApiServer:
    enabled: false

  kubelet:
    enabled: false

  kubeControllerManager:
    enabled: false

  coreDns:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  kubeStateMetrics:
    enabled: false

  nodeExporter:
    enabled: false

  prometheusOperator:
    enabled: false

  prometheus:
    enabled: false
