apiVersion: v2
name: external-dns-unifi
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: external-dns # https://github.com/kubernetes-sigs/external-dns/tree/master/charts/external-dns
    repository: https://kubernetes-sigs.github.io/external-dns/
    version: ">=1.15.0"
