# https://github.com/kashalls/external-dns-unifi-webhook
---
external-dns:
  labelFilter: unifi-dns=true
  provider:
    name: webhook
    webhook:
      image:
        repository: ghcr.io/kashalls/external-dns-unifi-webhook
        tag: v0.6.2
      env:
        - name: UNIFI_HOST
          value: https://192.168.1.254
        - name: UNIFI_EXTERNAL_CONTROLLER
          value: 'false'
        - name: UNIFI_API_KEY
          valueFrom:
            secretKeyRef:
              name: unifi-credentials
              key: api-key
        - name: LOG_LEVEL
          value: info
      livenessProbe:
        httpGet:
          path: /healthz
          port: http-webhook
        initialDelaySeconds: 10
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /readyz
          port: http-webhook
        initialDelaySeconds: 10
        timeoutSeconds: 5
  policy: sync
  sources: ['service']
  txtOwnerId: default
  txtPrefix: k8s.
  domainFilters: ['drewburr.com']

  serviceMonitor:
    enabled: true
