# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nfs-lake
# spec:
#   accessModes:
#   # - ReadWriteOnce
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: nfs-lake
