#!/bin/bash
# Scale every workload that has a PVC on storage01 to zero so the pools are quiescent.
# Records current replica counts to state/replicas.txt for scale-up.sh.
# Usage: ./scale-down.sh            (from this directory; needs kubectl context for the lab cluster)
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p state
STATE=state/replicas.txt
if [ -s "$STATE" ]; then
  echo "$STATE already exists; scale-up.sh has not been run since the last scale-down. Refusing to overwrite." >&2
  exit 1
fi

# The prometheus Application is ArgoCD auto-synced with selfHeal, which would undo the scale-down.
# It is generated by the ApplicationSet drewburr-apps, which re-adds the automated block within seconds,
# so the applicationset controller has to be stopped first. (The argocd Application itself is manual sync.)
echo "== stopping the ArgoCD applicationset controller"
asr=$(kubectl -n argocd get deploy argocd-applicationset-controller -o jsonpath='{.spec.replicas}')
echo "$asr" > state/applicationset-controller-replicas.txt
kubectl -n argocd scale deploy argocd-applicationset-controller --replicas=0
kubectl -n argocd rollout status deploy argocd-applicationset-controller --timeout=60s

echo "== disabling ArgoCD automated sync on prometheus"
kubectl -n argocd get application prometheus -o jsonpath='{.spec.syncPolicy.automated}' > state/prometheus-syncpolicy.json
echo >> state/prometheus-syncpolicy.json
kubectl -n argocd patch application prometheus --type=json -p '[{"op":"remove","path":"/spec/syncPolicy/automated"}]'

echo "== suspending CronJobs"
grep -v '^#' cronjobs.txt | while read -r ns name; do
  [ -z "$ns" ] && continue
  kubectl -n "$ns" patch cronjob "$name" -p '{"spec":{"suspend":true}}'
done

echo "== recording replicas and scaling to 0"
grep -v '^#' workloads.txt | while read -r kind ns name; do
  [ -z "$kind" ] && continue
  r=$(kubectl -n "$ns" get "$kind" "$name" -o jsonpath='{.spec.replicas}')
  echo "$kind $ns $name $r" >> "$STATE"
  if [ "$r" != "0" ]; then
    kubectl -n "$ns" scale "$kind" "$name" --replicas=0
  else
    echo "$kind/$name in $ns already at 0"
  fi
done

echo "== waiting for pods to terminate"
for i in $(seq 1 60); do
  left=$(grep -v '^#' workloads.txt | while read -r kind ns name; do
    [ -z "$kind" ] && continue
    sel=$(kubectl -n "$ns" get "$kind" "$name" -o jsonpath='{.spec.selector.matchLabels}' | python3 -c 'import json,sys; print(",".join(f"{k}={v}" for k,v in json.load(sys.stdin).items()))')
    kubectl -n "$ns" get pods -l "$sel" --no-headers 2>/dev/null || true
  done | wc -l)
  [ "$left" = "0" ] && break
  echo "  $left pods still present..."; sleep 10
done

echo "== leftover Job pods from the suspended CronJobs (completed ones are harmless)"
kubectl -n plex get pods --no-headers | grep -E "seeding-guard|missing-cleanup|series-reconciler" || echo "  none"

echo "== done. Verify on storage01 that no NVMe-oF/NFS clients remain:"
echo "   ssh storage01.drewburr.com 'ss -tn state established \"( sport = :4420 )\" | tail -n +2 | wc -l; ss -tn state established \"( sport = :2049 )\" | tail -n +2 | wc -l'"
