---
apiVersion: v2
name: argocd
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: argo-cd # https://artifacthub.io/packages/helm/argo/argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 5.46.7
    alias: argocd
