---
argocd:
  global:
    addPrometheusAnnotations: true

  configs:
    params:
      applicationsetcontroller.enable.new.git.file.globbing: "true"
      controller.sharding.algorithm: round-robin

  redis-ha:
    enabled: true
    metrics:
      enabled: true
    redis:
      resources:
        limits:
          cpu: 2
          memory: 256Mi
        requests:
          cpu: 500m
          memory: 100Mi
    haproxy:
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 100Mi

  controller:
    replicas: 2
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 256Mi

  server:
    replicas: 3
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 100Mi

    ingress:
      enabled: true
      https: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hostname: argocd.drewburr.com
      ingressClassName: nginx-internal
      tls: true

  repoServer:
    replicas: 2
    metrics:
      enabled: true
    resources:
      limits:
        cpu: 1
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 256Mi

  applicationSet:
    replicas: 2
    metrics:
      enabled: true
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 100Mi
