---
argocd:
  global:
    addPrometheusAnnotations: true

  configs:
    params:
      applicationsetcontroller.enable.new.git.file.globbing: "true"

  redis-ha:
    enabled: true
    metrics:
      enabled: true

  controller:
    replicas: 2
    metrics:
      enabled: true

  server:
    replicas: 3
    metrics:
      enabled: true

    ingress:
      enabled: true
      https: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hostname: argocd.drewburr.com
      ingressClassName: traefik
      tls: true

  repoServer:
    replicas: 2
    metrics:
      enabled: true

  applicationSet:
    replicas: 2
    metrics:
      enabled: true
