{{- with .Values.serviceMonitor }}
{{- if .enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minecraft-metrics
  namespace: {{ $.Release.Namespace }}
  labels:
    release: prometheus
spec:
  endpoints:
  {{- toYaml .endpoints | nindent 2 }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    {{- toYaml .selector | nindent 4 }}
{{- end }}
{{- end }}
