---
# Default values for printstream.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  port: 8080
  targetPort: 8080
  externalName: k1c.drewburr.com

ingress:
  enabled: true
  className: nginx-external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: ip.drewburr.com
    nginx.ingress.kubernetes.io/enable-gzip: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/stream.*$ /?action=stream break;
      rewrite ^/snapshot.*$ /?action=snapshot break;
    nginx.ingress.kubernetes.io/location-snippet: |
      if ($request_method !~ ^(GET)$ ) {
        return 405;
      }
  hosts:
    - host: printstream.drewburr.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: printstream-tls
      hosts:
        - printstream.drewburr.com
