apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "geist-pdu-exporter.fullname" . }}
  labels:
    release: prometheus
    {{- include "geist-pdu-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: http
    path: /
    interval: {{ .Values.serviceMonitor.endpoint.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.endpoint.scrapeTimeout }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector: {}
