authentik:
  postgresql:
    host: file:///postgres-creds/pgbouncer-host
    user: file:///postgres-creds/user
    password: file:///postgres-creds/password
  redis:
    host: redis.domain.tld
  server:
    volumes:
      - name: postgres-creds
        secret:
          secretName: authentik-postgres-credentials
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true
  worker:
    volumes:
      - name: postgres-creds
        secret:
          secretName: authentik-pguser-authentik
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true

postgrescluster:
  postgresVersion: 17

  instances:
    - name: postgres
      replicas: 2
      resources:
        # requests:
        limits:
          cpu: 1
          memory: 2Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: zfs-nvmeof
        resources:
          requests:
            storage: 10Gi

  users:
    - name: authentik

  pgBackRestConfig:
    global:
      repo1-retention-archive: '14' # Keep 14 backups worth of WAL
      repo1-retention-archive-type: incr # Consider all backup types when counting
      repo1-retention-diff: '14' # Keep 14 differential backups
      repo1-retention-full: '30' # Keep at least 30 days worth of full backups
      repo1-retention-full-type: time

    jobs:
      ttlSecondsAfterFinished: 86400 # Keep backup pods for 24 hours

    repos:
      - name: repo1
        schedules:
          full: 0 23 * * 5 # 23:00+00 Friday
          differential: 0 23 * * 0-4,6-7 # 23:00+00 excluding Friday
        volume:
          volumeClaimSpec:
            storageClassName: zfs-nfs
            accessModes:
            - "ReadWriteMany"
            resources:
              requests:
                storage: 20Gi

  pgBouncerReplicas: 1
  pgBouncerConfig: {}

  monitoring: true
