{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mc-router
  labels:
    release: prometheus
spec:
  endpoints:
  - port: http
    path: /
    interval: {{ .Values.serviceMonitor.endpoint.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.endpoint.scrapeTimeout }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      - metrics: "true"
{{- end }}
