---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: archiveteam-grab
  labels:
    app: archiveteam-grab
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: archiveteam-grab
  template:
    metadata:
      labels:
        app: archiveteam-grab
    spec:
      containers:
        - name: archiveteam-grab
          image: {{ .Values.image }}
          args:
            - '--concurrent'
            - {{ .Values.grabArgs.concurrency | quote }}
            - {{ .Values.grabArgs.username | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: grab-data
              mountPath: "/grab"{{ if not .Values.persistence.encapsulateWorkdir }}"/data"{{ end }}
          imagePullPolicy: Always
      {{- if .Values.persistence.encapsulateWorkdir }}
      initContainers:
        - name: copy-grab
          image: {{ .Values.image }}
          command:
            - cp
            - -R
            - /grab/*
            - /pvc
          volumeMounts:
            - name: grab-data
              mountPath: /pvc
          imagePullPolicy: Always
      {{- end }}
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.persistence.unified }}
      volumes:
        - name: grab-data
          persistentVolumeClaim:
            claimName: grab-data
      {{- end }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- if not .Values.persistence.unified }}
  volumeClaimTemplates:
  - metadata:
      name: grab-data
    spec:
      accessModes:
        {{- toYaml .Values.persistence.accessModes | nindent 8 }}
      resources:
        {{- toYaml .Values.persistence.resources | nindent 8 }}
      storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
