---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: archiveteam-grab
  labels:
    app: archiveteam-grab
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: archiveteam-grab
  template:
    metadata:
      labels:
        app: archiveteam-grab
    spec:
      containers:
        - name: archiveteam-grab
          image: {{ .Values.image }}
          args:
            - '--concurrent'
            - {{ .Values.grabArgs.concurrency | quote }}
            - '--disable-web-server'
            - {{ .Values.grabArgs.username | quote }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: grab-data
              mountPath: /grab/data
          imagePullPolicy: Always
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      terminationGracePeriodSeconds: 300
      {{- if .Values.persistence.unified }}
      volumes:
        - name: grab-data
          persistentVolumeClaim:
            claimName: grab-data
      {{- end }}
  {{- if not .Values.persistence.unified }}
  volumeClaimTemplates:
  - metadata:
      name: grab-data
    spec:
      accessModes:
        {{ toYaml .Values.persistence.accessModes | nindent 4 }}
      resources:
        {{ toYaml .Values.persistence.resources | nindent 4 }}
      storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
