---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mildom-grab
  labels:
    app: mildom-grab
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: mildom-grab
  template:
    metadata:
      labels:
        app: mildom-grab
    spec:
      containers:
        - name: mildom-grab
          image: {{ .Values.image }}
          args:
            - '--concurrent'
            - {{ .Values.grabArgs.concurrency | quote }}
            - '--disable-web-server'
            - {{ .Values.grabArgs.username | quote }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cache-volume
              mountPath: /grab/data
          imagePullPolicy: Always
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      terminationGracePeriodSeconds: 300
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: mildom-grab-{{ .Values.persistence.name }}
