apiVersion: v2
name: flare-bypasser
description: A Helm chart for deploying flare-bypasser
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
- name: library
  version: 0.0.0
  repository: file://../library
