apiVersion: v2
name: sonarr
description: A Helm chart for deploying sonarr
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
- name: library
  version: 0.0.0
  repository: file://../library
