---
ingress-nginx:
  ingressClassResource:
    name: nginx-external

  controller:
    kind: Daemonset

    resources:
      requests:
        cpu: 100m
        memory: 90Mi

    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: '192.168.4.62'

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
