---
ingress-nginx:

  controller:
    kind: Daemonset

    ingressClassResource:
      name: nginx-external
    ingressClass: nginx-external
    controllerValue: k8s.io/ingress-nginx-external

    resources:
      requests:
        cpu: 100m
        memory: 90Mi

    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: '192.168.4.62'

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
