---
ingress-nginx:

  controller:
    kind: DaemonSet

    admissionWebhooks:
      enabled: false

    ingressClassResource:
      name: nginx-external
      controllerValue: k8s.io/ingress-nginx-external
    ingressClass: nginx-external

    resources:
      requests:
        cpu: 100m
        memory: 90Mi

    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: '192.168.4.62'

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  tcp: {}

  udp:
    24455: "minecraft-jinkies/minecraft:simple-vc"
