# Default values for panel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/crafty-controller/crafty-4
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

livenessProbe:
  initialDelaySeconds: 30
  httpGet:
    path: /
    port: https
    scheme: HTTPS
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 18
  httpGet:
    path: /
    port: https
    scheme: HTTPS
startupProbe: {}

persistence:
  - name: crafty-backups
    mountPath: /crafty/backups
    accessModes:
      - ReadWriteOnce
    requests: 50Gi
    storageClassName: zfs-nvmeof
  - name: crafty-logs
    mountPath: /crafty/logs
    accessModes:
      - ReadWriteOnce
    requests: 5Gi
    storageClassName: zfs-nvmeof
  - name: crafty-servers
    mountPath: /crafty/servers
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof
  - name: crafty-app-config
    mountPath: /crafty/app/config
    accessModes:
      - ReadWriteOnce
    requests: 1Gi
    storageClassName: zfs-nvmeof
  - name: crafty-import
    mountPath: /crafty/import
    accessModes:
      - ReadWriteOnce
    requests: 5Gi
    storageClassName: zfs-nvmeof

additionalVolumes: []

additionalVolumeMounts: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

podAnnotations: {}

podSecurityContext:
  # {}
  fsGroup: 0

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000 # Built-in Crafty user

initContainers:
  - name: sftp
    image:
      repository: atmoz/sftp
      tag: apline
    ports:
      - name: sftp
        conatinerPort: 22
        protocol: TCP
    resources: {}
    env:
      - name: SFTP_USERS
        value: 'test:password:1000:0:'
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000 # Built-in Crafty user
    livenessProbe:
      initialDelaySeconds: 30
      tcpSocket:
        port: sftp
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 10
      tcpSocket:
        port: sftp
    volumeMounts: []

services:
  - name: https
    type: ClusterIP
    ports:
      - name: https
        port: 8443
        protocol: TCP
    ingress:
      className: nginx-external
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        external-dns.alpha.kubernetes.io/target: ip.drewburr.com
        nginx.ingress.kubernetes.io/configuration-snippet: |
          sub_filter '<a class="nav-link" href="/panel/contribute">' '<a class="nav-link" href="/panel/contribute" hidden=true>';
          sub_filter '<a class="nav-link" href="/panel/credits">' '<a class="nav-link" href="/panel/credits" hidden=true>';
          sub_filter '<a class="nav-link" href="https://discord.gg/9VJPhCE" target="_blank">' '<a class="nav-link" hidden=true>';
      hosts:
        - host: test.crafty.drewburr.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: craftycontroller-ingress
          hosts:
            - test.crafty.drewburr.com
  - name: minecraft
    type: ClusterIP
    annotations:
      mc-router.itzg.me/externalServerName: test.mc.drewburr.com
    ports:
      - name: minecraft
        port: 25565
        protocol: TCP

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}
