# Default values for panel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/crafty-controller/crafty-4
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

livenessProbe:
  httpGet:
    path: /
    port: https
    scheme: HTTPS
readinessProbe:
  httpGet:
    path: /
    port: https
    scheme: HTTPS
startupProbe: {}

persistence:
  - name: crafty-backups
    mountPath: /crafty/backups
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof
  - name: crafty-logs
    mountPath: /crafty/logs
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof
  - name: crafty-servers
    mountPath: /crafty/servers
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof
  - name: crafty-app-config
    mountPath: /crafty/app/config
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof
  - name: crafty-import
    mountPath: /crafty/import
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof

additionalVolumes: []

additionalVolumeMounts: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

podAnnotations: {}

podSecurityContext:
  # {}
  fsGroup: 0

securityContext:
  # {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1001

initContainers: []

services:
  - name: https
    type: ClusterIP
    ports:
      - name: https
        port: 8443
        protocol: TCP
    ingress:
      className: nginx-external
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: ip.drewburr.com
        cloudflare-dns: 'true'
      hosts:
        - host: craftycontroller.drewburr.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: craftycontroller-ingress
          hosts:
            - craftycontroller.drewburr.com
  - name: minecraft
    type: ClusterIP
    annotations:
      mc-router.itzg.me/externalServerName: craftycontroller.mc.drewburr.com
    ports:
      - name: minecraft
        port: 25565
        protocol: TCP

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
