---
apiVersion: v2
name: metallb
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: metallb # https://github.com/metallb/metallb/tree/main/charts/metallb
    repository: https://metallb.github.io/metallb
    version: ">=0.14.8"
