{
 "title": "Geist PDU Usage Overview",
 "time": { "from": "2024-08-10T18:21:52.624Z", "to": "2024-08-11T02:32:01.075Z" },
 "templating": {
  "list": [
   { "name": "kwh_cost", "query": "0.11661" }
  ]
 },
 "panels": [
  {
   "title": "Operating Cost (Selected Interval)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (type)(pdu_kwh_total) * $kwh_cost",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cost per Outlet (Selected Interval)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum by (num, name)(pdu_outlet_kwh_total) * $kwh_cost",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total KWh Used (Selected Interval)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    { "expr": "sum by (type)(pdu_kwh)", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Input Amperage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "sum by (type)(pdu_amps)", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "sum by (type)(pdu_volts)", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Total Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (type)(pdu_power_factor_percent)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Outlet Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Amperage per Outlet",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "sum by (name, num)(pdu_outlet_amps)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wattage per Outlet (Real Power)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (name, num)(pdu_outlet_watts)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Factor per Outlet",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (name, num)(pdu_outlet_watts) / (sum by (name, num)(pdu_outlet_amps) * ignoring(name, num) group_left sum(pdu_volts))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}