# Default values for panel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/crafty-controller/crafty-4
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

livenessProbe:
  initialDelaySeconds: 30
  httpGet:
    path: /
    port: https
    scheme: HTTPS
readinessProbe:
  initialDelaySeconds: 30
  failureThreshold: 9
  httpGet:
    path: /
    port: https
    scheme: HTTPS
startupProbe: {}

persistence:
  - name: crafty-backups
    mountPath: /crafty/backups
    accessModes:
      - ReadWriteOnce
    requests: 250Gi
    storageClassName: zfs-nvmeof
  - name: crafty-logs
    mountPath: /crafty/logs
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof
  - name: crafty-servers
    mountPath: /crafty/servers
    accessModes:
      - ReadWriteOnce
    requests: 100Gi
    storageClassName: zfs-nvmeof
  - name: crafty-app-config
    mountPath: /crafty/app/config
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof
  - name: crafty-import
    mountPath: /crafty/import
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof

additionalVolumes: []

additionalVolumeMounts: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

podAnnotations: {}

podSecurityContext:
  # {}
  fsGroup: 0

securityContext:
  # {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1001

initContainers: []

services:
  - name: https
    type: ClusterIP
    ports:
      - name: https
        port: 8443
        protocol: TCP
    ingress:
      className: nginx-internal
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
        - host: jinkies.crafty.drewburr.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: craftycontroller-ingress
          hosts:
            - jinkies.crafty.drewburr.com
  - name: minecraft
    type: ClusterIP
    annotations:
      mc-router.itzg.me/externalServerName: jinkies.mc.drewburr.com
    ports:
      - name: minecraft
        port: 25565
        protocol: TCP
  - name: voice-chat
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: '192.168.4.65'
    ports:
      - name: simple-vc # Must be configured under ingress-nginx-external/values.yaml:ingress-nginx.udp
        port: 24455
        protocol: UDP

resources:
  limits:
    cpu: 2
    memory: 9Gi
  requests:
    cpu: 2
    memory: 9Gi

nodeSelector: {}

tolerations: []

affinity: {}
