# Default values for panel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/crafty-controller/crafty-4
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

livenessProbe:
  initialDelaySeconds: 30
  httpGet:
    path: /
    port: https
    scheme: HTTPS
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 18
  httpGet:
    path: /
    port: https
    scheme: HTTPS
startupProbe: {}

persistence:
  - name: crafty-backups
    mountPath: /crafty/backups
    accessModes:
      - ReadWriteOnce
    requests: 250Gi
    storageClassName: zfs-nvmeof
  - name: crafty-logs
    mountPath: /crafty/logs
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof
  - name: crafty-servers
    mountPath: /crafty/servers
    accessModes:
      - ReadWriteOnce
    requests: 100Gi
    storageClassName: zfs-nvmeof
  - name: crafty-app-config
    mountPath: /crafty/app/config
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof
  - name: crafty-import
    mountPath: /crafty/import
    accessModes:
      - ReadWriteOnce
    requests: 10Gi
    storageClassName: zfs-nvmeof

additionalVolumes:
  - name: sftp-run
    emptyDir: {}
  - name: sftp-host-keys
    secret:
      secretName: sftp-host-keys
  - name: sftp-scripts
    configMap:
      name: sftp-scripts
      defaultMode: 0550

additionalVolumeMounts: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

podAnnotations: {}

podSecurityContext: {}

securityContext:
  # {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000 # Built-in Crafty user

initContainers:
  - name: sftp
    image:
      repository: atmoz/sftp
      tag: alpine
    ports:
      - name: sftp
        port: 22
        protocol: TCP
    resources: {}
    env:
      - name: SFTP_USERS
        valueFrom:
          secretKeyRef:
            name: sftp-users
            key: users
    livenessProbe:
      tcpSocket:
        port: sftp
    readinessProbe:
      tcpSocket:
        port: sftp
    restartPolicy: Always
    volumeMounts:
      - name: sftp-run
        mountPath: /var/run
      - name: sftp-host-keys
        mountPath: /etc/ssh-keys
      - name: sftp-scripts
        mountPath: /etc/sftp.d
      - name: crafty-backups
        mountPath: /home/crafty/backups
      - name: crafty-logs
        mountPath: /home/crafty/crafty-logs
      - name: crafty-servers
        mountPath: /home/crafty/servers
      - name: crafty-import
        mountPath: /home/crafty/import

services:
  - name: https
    type: ClusterIP
    ports:
      - name: https
        port: 8443
        protocol: TCP
    ingress:
      className: nginx-external
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        external-dns.alpha.kubernetes.io/target: ip.drewburr.com
        nginx.ingress.kubernetes.io/proxy-body-size: "0" # Disable size check
        nginx.ingress.kubernetes.io/configuration-snippet: |
          sub_filter '<a class="nav-link" href="/panel/contribute">' '<a class="nav-link" href="/panel/contribute" hidden=true>';
          sub_filter '<a class="nav-link" href="/panel/credits">' '<a class="nav-link" href="/panel/credits" hidden=true>';
          sub_filter '<a class="nav-link" href="https://discord.gg/9VJPhCE" target="_blank">' '<a class="nav-link" hidden=true>';
      hosts:
        - host: jinkies.crafty.drewburr.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: craftycontroller-ingress
          hosts:
            - jinkies.crafty.drewburr.com
  - name: minecraft
    type: ClusterIP
    annotations:
      mc-router.itzg.me/externalServerName: jinkies.mc.drewburr.com
    ports:
      - name: minecraft
        port: 25565
        protocol: TCP
  - name: voice-chat
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: '192.168.4.65'
    ports:
      - name: simple-vc
        port: 24455
        protocol: UDP
  - name: sftp
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: '192.168.4.52'
    ports:
      - name: sftp
        port: 22
        protocol: TCP
  - name: metrics
    type: ClusterIP
    labels:
      metrics: "true"
    ports:
      - name: metrics
        port: 19565
        protocol: TCP

resources:
  limits:
    cpu: 5
    memory: 12Gi
  requests:
    cpu: 2
    memory: 12Gi

nodeSelector: {}

tolerations: []

affinity: {}
