apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    ports:
    - name: test
      containerPort: 80
    - name: test
      containerPort: 443
  dnsPolicy: ClusterFirst
  restartPolicy: Always
