{{- with .Values.gpuDevicePlugin }}
apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: gpudeviceplugin-sample
spec:
  image: {{ .image.path }}:{{ .image.tag }}
  # https://intel.github.io/intel-device-plugins-for-kubernetes/cmd/gpu_plugin/README.html#modes-and-configuration-options
  sharedDevNum: {{ .sharedDevNum }}
  logLevel: {{ .logLevel }}
  enableMonitoring: {{ .enableMonitoring }}
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true" # Set by NFD NodeFeatureRule
{{- end }}
